:asset_root: public
:load_path:
  - app/javascripts
  - app/javascripts/vendor
  - vendor/sprockets/*/src
  - vendor/plugins/*/javascripts
:source_files:
  - app/javascripts/application.js
  - app/javascripts/**/*.js
